apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: chom08qn5-nodejs
  janus-idp.io/tekton: chom08qn5-nodejs
  backstage.io/kubernetes-id: chom08qn5-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: chom08qn5-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
